/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export function Model(props) {
  const { nodes, materials } = useGLTF('/floatingIsland.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere009.geometry}
        material={materials.Island}
        position={[-11.199, -5.648, -22.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert002.geometry}
        material={materials.Land}
        position={[-11.475, -0.004, -23.373]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Pillar}
        position={[-13.453, 2.357, -22.296]}
        rotation={[0, 0.192, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Pillar}
        position={[-18.326, 2.357, -22.152]}
        rotation={[0, 0.192, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Pillar}
        position={[-21.903, 2.357, -25.578]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.Pillar}
        position={[-13.779, 2.357, -34.098]}
        rotation={[0, 0.192, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.Pillar}
        position={[-18.596, 2.357, -33.936]}
        rotation={[0, 0.192, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.Pillar}
        position={[-21.983, 2.357, -30.4]}
        rotation={[0, 0.192, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.Pillar}
        position={[-10.244, 2.357, -30.756]}
        rotation={[0, 0.192, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials.Pillar}
        position={[-10.057, 2.357, -25.689]}
        rotation={[0, 0.192, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-16.005, 1.096, -28.098]}
        rotation={[0, 0.411, 0]}
        scale={0.925}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials.Pillar}
        position={[-18.315, 7.146, -22.176]}
        rotation={[0, -0.147, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials.Pillar}
        position={[-20.345, 8.072, -29.801]}
        rotation={[0, -0.384, -0.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.Pillar}
        position={[-15.971, 9.099, -27.993]}
        rotation={[0, -0.147, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.Pillar}
        position={[-17.263, 10.524, -30.948]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Pillar}
        position={[-15.971, 11.936, -27.993]}
        rotation={[0, -0.147, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Pillar}
        position={[-17.64, 12.925, -28.684]}
        rotation={[0, -0.384, -0.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Fence}
        position={[-14.5, 2.644, -22.187]}
        rotation={[0, 0.019, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Fences Top']}
        position={[-15.886, 3.48, -22.177]}
        rotation={[0, 0.019, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Fences Top']}
        position={[-15.928, 9.621, -24.926]}
        rotation={[0, 0.023, 0]}
        scale={[1.35, 0.25, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Roof}
        position={[-15.928, 9.469, -24.926]}
        rotation={[0, 0.023, 0]}
        scale={[1.35, 0.25, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[-16.005, 14.159, -28.098]}
        scale={[1, 0.75, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials.Roof}
        position={[-16.005, 14.142, -28.098]}
        scale={[1, 0.75, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Stairs}
        position={[-10.874, 1.173, -23.071]}
        rotation={[0, 0.805, 0]}
        scale={[1.5, 0.5, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert003.geometry}
        material={materials.Land}
        position={[-19.853, -1.388, 17.377]}
        rotation={[0, -0.098, 0]}
        scale={[3.895, 0.635, 0.635]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere017.geometry}
        material={materials.Island}
        position={[-20.953, -8.113, 20.07]}
        rotation={[-0.041, 0.964, -0.095]}
        scale={[0.17, 0.895, 0.582]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert001.geometry}
        material={materials.Land}
        position={[27.689, -3.821, 5.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere007.geometry}
        material={materials.Island}
        position={[27.098, -5.531, 5.525]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern.geometry}
        material={materials.Lantern}
        position={[-5.257, 2.02, -31.322]}
        rotation={[0, -0.531, 0]}
        scale={1.813}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp.geometry}
          material={materials['Lentern Glow']}
          position={[0.002, 1.017, 0.007]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern001.geometry}
        material={materials.Lantern}
        position={[-20.231, 1.561, -9.192]}
        rotation={[0, -1.364, 0]}
        scale={1.813}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp001.geometry}
          material={materials['Lentern Glow']}
          position={[0.002, 1.029, 0.007]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern002.geometry}
        material={materials.Lantern}
        position={[-1.337, 1.787, -11.334]}
        rotation={[0, -0.531, 0]}
        scale={1.813}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp002.geometry}
          material={materials['Lentern Glow']}
          position={[0.002, 1.021, 0.007]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern003.geometry}
        material={materials.Lantern}
        position={[30.219, -2.218, 10.678]}
        rotation={[0, -0.531, 0]}
        scale={1.813}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp003.geometry}
          material={materials['Lentern Glow']}
          position={[0.002, 1.026, 0.007]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern004.geometry}
        material={materials.Lantern}
        position={[-12.802, -2.424, 22.124]}
        rotation={[0, -0.531, 0]}
        scale={1.813}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp004.geometry}
          material={materials['Lentern Glow']}
          position={[0.002, 1.062, 0.007]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert.geometry}
        material={materials.Tree}
        position={[-23.937, 0.32, -18.257]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere015.geometry}
        material={materials.Leave}
        position={[-26.011, 10.655, -23.588]}
        rotation={[0.201, 0.067, -1.017]}
        scale={[0.646, 0.698, 0.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere016.geometry}
        material={materials.Leave}
        position={[-24.414, 8.547, -25.02]}
        rotation={[0.185, -0.103, -1.834]}
        scale={[0.399, 0.43, 0.482]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere018.geometry}
        material={materials.Leave}
        position={[-25.534, 9.789, -24.995]}
        rotation={[0.221, -0.428, -0.911]}
        scale={[0.715, 0.772, 0.865]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere019.geometry}
        material={materials.Leave}
        position={[-25.214, 10.144, -20.595]}
        rotation={[0.201, 0.067, -1.017]}
        scale={[0.763, 0.996, 0.784]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere020.geometry}
        material={materials.Leave}
        position={[-25.533, 11.585, -22.025]}
        rotation={[0.185, -0.103, -1.834]}
        scale={[0.399, 0.43, 0.482]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere021.geometry}
        material={materials.Leave}
        position={[-25.13, 9.953, -22.029]}
        rotation={[-0.799, -0.103, -1.834]}
        scale={[0.399, 0.43, 0.482]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere022.geometry}
        material={materials.Leave}
        position={[-25.218, 13.953, -18.415]}
        rotation={[0.834, -0.756, -0.625]}
        scale={[0.926, 1.208, 0.951]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere023.geometry}
        material={materials.Leave}
        position={[-24.784, 11.626, -19.235]}
        rotation={[-2.208, 0.102, 2.102]}
        scale={[0.817, 1.065, 0.839]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere024.geometry}
        material={materials.Leave}
        position={[-25.215, 10.144, -18.611]}
        rotation={[0.201, 0.067, -1.017]}
        scale={[0.646, 0.698, 0.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere025.geometry}
        material={materials.Leave}
        position={[-25.86, 12.724, -16.3]}
        rotation={[0.685, -0.551, -0.869]}
        scale={[0.856, 1.117, 0.879]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere026.geometry}
        material={materials.Leave}
        position={[-25.825, 11.111, -15.921]}
        rotation={[-0.017, -0.5, -2.354]}
        scale={[0.399, 0.43, 0.482]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere027.geometry}
        material={materials.Leave}
        position={[-26.69, 13.508, -13.501]}
        rotation={[-1.196, -1.159, -1.8]}
        scale={[0.926, 1.208, 0.951]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere028.geometry}
        material={materials.Leave}
        position={[-28.389, 10.542, -12.12]}
        rotation={[0.201, 0.067, -1.017]}
        scale={[0.646, 0.698, 0.782]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere029.geometry}
        material={materials.Leave}
        position={[-27.556, 11.646, -12.648]}
        rotation={[-0.799, -0.103, -1.834]}
        scale={[0.399, 0.43, 0.482]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere030.geometry}
        material={materials.Leave}
        position={[-26.968, 7.492, -13.349]}
        rotation={[-0.763, 0.227, -0.547]}
        scale={[0.887, 0.958, 1.072]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere031.geometry}
        material={materials.Leave}
        position={[-25.45, 5.916, -15.185]}
        rotation={[0.235, 0.492, -1.313]}
        scale={[0.555, 0.599, 0.671]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere032.geometry}
        material={materials.Leave}
        position={[-30.642, 11.627, -18.312]}
        rotation={[-2.496, -1.11, 1.987]}
        scale={[0.885, 1.154, 0.909]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere033.geometry}
        material={materials.Leave}
        position={[-27.37, 12.279, -19.686]}
        rotation={[2.883, -0.149, 1.802]}
        scale={[0.711, 0.927, 0.73]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere034.geometry}
        material={materials.Leave}
        position={[-28.64, 13.395, -16.093]}
        rotation={[-1.592, -1.289, -2.078]}
        scale={[0.926, 1.208, 0.951]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere035.geometry}
        material={materials.Leave}
        position={[-28.219, 12.833, -13.325]}
        rotation={[-0.763, 0.227, -0.547]}
        scale={[0.778, 0.84, 0.94]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere036.geometry}
        material={materials.Leave}
        position={[-28.082, 13.923, -18.657]}
        rotation={[0.185, -0.103, -1.834]}
        scale={[0.399, 0.43, 0.482]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere037.geometry}
        material={materials.Leave}
        position={[-30.001, 12.154, -21.437]}
        rotation={[-0.499, 1.249, -0.481]}
        scale={[0.555, 0.599, 0.671]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert004.geometry}
        material={materials.Tree}
        position={[-26.288, -3.756, 23.476]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere038.geometry}
        material={materials.Leave}
        position={[-24.882, 8.34, 27.91]}
        scale={0.962}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere039.geometry}
        material={materials.Leave}
        position={[-27.114, 9.029, 25.555]}
        rotation={[0.378, 0, 0]}
        scale={[1.724, 1.724, 2.652]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere040.geometry}
        material={materials.Leave}
        position={[-27.847, 7.554, 23.375]}
        rotation={[0.113, 0.892, 0]}
        scale={[1.524, 1.087, 3.982]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere041.geometry}
        material={materials.Leave}
        position={[-30.35, 6.654, 19.853]}
        rotation={[-2.624, 1.34, 2.57]}
        scale={[1.316, 0.568, 1.971]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere042.geometry}
        material={materials.Leave}
        position={[-33.202, 5.09, 18.868]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere043.geometry}
        material={materials.Leave}
        position={[-26.046, 8.917, -14.732]}
        rotation={[0.848, 0.061, -0.246]}
        scale={[0.856, 1.117, 0.879]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Water}
        position={[-23.421, -3.969, 18.446]}
        scale={[6.52, 6.52, 5.182]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere044.geometry}
        material={materials.Rock}
        position={[-23.115, -3.015, 25.806]}
        rotation={[0.308, 0, 0.362]}
        scale={[1.193, 1.539, 0.733]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere045.geometry}
        material={materials.Rock}
        position={[-20.97, -2.945, 26.481]}
        rotation={[0.177, -0.096, -0.407]}
        scale={[1.193, 1.539, 0.733]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere046.geometry}
        material={materials.Rock}
        position={[-26.636, -3.688, 12.341]}
        scale={[0.535, 0.221, 0.339]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere047.geometry}
        material={materials.Rock}
        position={[-22.637, -3.688, 12.341]}
        scale={[0.407, 0.139, 0.433]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere048.geometry}
        material={materials.Rock}
        position={[-12.874, -3.742, 16.751]}
        scale={[0.656, 0.143, 0.332]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere049.geometry}
        material={materials.Rock}
        position={[-13.507, 0.189, -2.426]}
        rotation={[-0.208, -0.286, 0.065]}
        scale={[0.718, 0.116, 0.447]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere050.geometry}
        material={materials.Rock}
        position={[-13.432, -0.119, -0.542]}
        rotation={[-0.057, -0.464, 0.168]}
        scale={[1.332, 0.176, 0.524]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere051.geometry}
        material={materials.Rock}
        position={[-13.73, -0.689, 1.631]}
        rotation={[-0.082, -0.518, 0.169]}
        scale={[1.685, 0.223, 0.662]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere052.geometry}
        material={materials.Rock}
        position={[-14.299, -1.13, 4.31]}
        rotation={[0.032, -0.62, 0.195]}
        scale={[1.685, 0.223, 0.662]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere053.geometry}
        material={materials.Rock}
        position={[-15.243, -1.587, 7.012]}
        rotation={[0.872, -1.371, 1.069]}
        scale={[1.159, 0.221, 1.217]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere054.geometry}
        material={materials.Rock}
        position={[-17.398, -2.695, 9.164]}
        rotation={[2.47, -1.352, 2.781]}
        scale={[1.159, 0.221, 1.217]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere055.geometry}
        material={materials.Rock}
        position={[-19.06, -3.563, 11.508]}
        rotation={[2.47, -1.352, 2.781]}
        scale={[1.313, 0.25, 1.378]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere056.geometry}
        material={materials.Rock}
        position={[9.557, 0.575, -20.415]}
        scale={[0.614, 0.184, 0.614]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere057.geometry}
        material={materials.Rock}
        position={[11.939, 0.179, -19.719]}
        rotation={[0, -0.254, 0]}
        scale={[0.576, 0.236, 0.793]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere058.geometry}
        material={materials.Rock}
        position={[14.411, -0.33, -18.608]}
        rotation={[0, -0.424, 0]}
        scale={[0.846, 0.236, 1.459]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere059.geometry}
        material={materials.Rock}
        position={[17.375, -0.794, -17.31]}
        rotation={[0.199, -0.715, 0.243]}
        scale={[1.049, 0.292, 1.81]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere060.geometry}
        material={materials.Rock}
        position={[20.557, -0.918, -14.323]}
        rotation={[0.259, -0.984, 0.322]}
        scale={[1.095, 0.305, 1.889]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere061.geometry}
        material={materials.Rock}
        position={[23.537, -1.422, -11.361]}
        rotation={[0.444, -1.108, 0.583]}
        scale={[1.16, 0.323, 2.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere062.geometry}
        material={materials.Rock}
        position={[24.7, -2.108, -7.502]}
        rotation={[0.557, -1.199, 0.706]}
        scale={[1.16, 0.323, 2.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere063.geometry}
        material={materials.Rock}
        position={[25.694, -2.989, -4.126]}
        rotation={[1.477, -1.459, 1.629]}
        scale={[1.16, 0.323, 2.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere064.geometry}
        material={materials.Rock}
        position={[25.809, -3.317, -1.133]}
        rotation={[1.477, -1.459, 1.629]}
        scale={[1.16, 0.323, 2.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere065.geometry}
        material={materials.Rock}
        position={[-3.68, 0.909, -8.209]}
        rotation={[-0.692, 0.249, 0.368]}
        scale={[1.705, 0.871, 1.166]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere066.geometry}
        material={materials.Rock}
        position={[-1.332, 0.51, -9.165]}
        rotation={[0, 0, -0.293]}
        scale={[1.221, 0.599, 1.117]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks02.geometry}
        material={materials.ImphenziaPixPal}
        position={[-14.507, 0.736, -18.128]}
        rotation={[0.013, 0, -0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks02001.geometry}
        material={materials.ImphenziaPixPal}
        position={[-7.611, 0.724, -21.217]}
        rotation={[0.014, 0.329, -0.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks01.geometry}
        material={materials.ImphenziaPixPal}
        position={[-12.393, 0.728, -18.719]}
        rotation={[2.815, -1.53, 2.808]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks02002.geometry}
        material={materials.ImphenziaPixPal}
        position={[0.766, 0.63, -24.431]}
        rotation={[-0.114, 1.499, 0.096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks01001.geometry}
        material={materials.ImphenziaPixPal}
        position={[1.643, 0.589, -16.135]}
        rotation={[0.364, -0.479, -0.024]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks01002.geometry}
        material={materials.ImphenziaPixPal}
        position={[-3.122, 0.695, -21.592]}
        rotation={[0.056, -1.339, 0.047]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks02003.geometry}
        material={materials.ImphenziaPixPal}
        position={[-4.869, 0.634, -15.874]}
        rotation={[0.018, -0.75, 0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks01003.geometry}
        material={materials.ImphenziaPixPal}
        position={[-13.957, 0.617, -9.207]}
        rotation={[0.019, 0.807, -0.021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks02004.geometry}
        material={materials.ImphenziaPixPal}
        position={[-0.233, 0.604, -29.868]}
        rotation={[-0.016, 1.017, -0.005]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks01004.geometry}
        material={materials.ImphenziaPixPal}
        position={[-9.68, 0.663, -15.289]}
        rotation={[0.044, -1.27, 0.034]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks01005.geometry}
        material={materials.ImphenziaPixPal}
        position={[-7.593, 0.695, -34.877]}
        rotation={[-0.125, -1.505, -0.143]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks02005.geometry}
        material={materials.ImphenziaPixPal}
        position={[-5.118, 0.709, -27.772]}
        rotation={[-0.015, -0.974, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GroundRocks01006.geometry}
        material={materials.ImphenziaPixPal}
        position={[-21.795, 0.619, -15.444]}
        rotation={[1.054, -1.535, 1.098]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brush01.geometry}
        material={materials.ImphenziaPixPal}
        position={[33.926, -3.366, 9.928]}
        rotation={[0, -1.179, 0]}
        scale={5.248}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brush01001.geometry}
        material={materials.ImphenziaPixPal}
        position={[20.523, -3.366, 3.978]}
        scale={5.665}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HayStack01.geometry}
        material={materials.ImphenziaPixPal}
        position={[33.284, -3.556, 2.806]}
        rotation={[0, -1.319, 0]}
        scale={1.767}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HayStack04.geometry}
        material={materials.ImphenziaPixPal}
        position={[23.863, -3.556, 10.562]}
        rotation={[0, -1.04, 0]}
        scale={2.212}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Brush01002.geometry}
        material={materials.ImphenziaPixPal}
        position={[-13.713, 0.873, -37.302]}
        rotation={[-2.341, -1.409, -2.342]}
        scale={3.316}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WoodPost03.geometry}
        material={materials.ImphenziaPixPal}
        position={[-4.476, 0.649, -31.91]}
        rotation={[0.753, -0.595, 1.02]}
        scale={1.673}
      />
    </group>
  )
}

useGLTF.preload('/floatingIsland.glb')
