/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/floatingIsland.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere009.geometry}
        material={materials.Island}
        position={[-0.1734, -5.6479, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert002.geometry}
        material={materials.Land}
        position={[-0.4489, -0.0044, -0.8898]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Pillar}
        position={[-2.427, 2.3568, 0.1867]}
        rotation={[0, 0.1922, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Pillar}
        position={[-7.3007, 2.3568, 0.3304]}
        rotation={[0, 0.1922, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Pillar}
        position={[-10.8772, 2.3568, -3.0955]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.Pillar}
        position={[-2.7535, 2.3568, -11.6154]}
        rotation={[0, 0.1922, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.Pillar}
        position={[-7.5699, 2.3568, -11.4534]}
        rotation={[0, 0.1922, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.Pillar}
        position={[-10.9577, 2.3568, -7.9173]}
        rotation={[0, 0.1922, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.Pillar}
        position={[0.7818, 2.3568, -8.2729]}
        rotation={[0, 0.1922, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials.Pillar}
        position={[0.969, 2.3568, -3.2058]}
        rotation={[0, 0.1922, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-4.9791, 1.096, -5.6155]}
        rotation={[0, 0.4115, 0]}
        scale={0.9249}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials.Pillar}
        position={[-7.2896, 7.1457, 0.3072]}
        rotation={[0, -0.1471, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials.Pillar}
        position={[-9.3192, 8.072, -7.3178]}
        rotation={[0, -0.384, -0.9599]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.Pillar}
        position={[-4.9456, 9.099, -5.5102]}
        rotation={[0, -0.1471, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.Pillar}
        position={[-6.2368, 10.5237, -8.465]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Pillar}
        position={[-4.9456, 11.9357, -5.5102]}
        rotation={[0, -0.1471, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Pillar}
        position={[-6.6141, 12.9247, -6.2012]}
        rotation={[0, -0.384, -0.9599]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Fence}
        position={[-3.4745, 2.6441, 0.2956]}
        rotation={[0, 0.0191, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Fences Top']}
        position={[-4.8607, 3.4801, 0.3053]}
        rotation={[0, 0.0191, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Fences Top']}
        position={[-4.9021, 9.6212, -2.4434]}
        rotation={[0, 0.0227, 0]}
        scale={[1.35, 0.25, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Roof}
        position={[-4.9021, 9.6212, -2.4434]}
        rotation={[0, 0.0227, 0]}
        scale={[1.35, 0.25, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[-4.9791, 14.1594, -5.6155]}
        scale={[1, 0.75, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials.Roof}
        position={[-4.9791, 14.1443, -5.6155]}
        scale={[1, 0.75, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Stairs}
        position={[0.152, 1.1731, -0.5879]}
        rotation={[0, 0.8048, 0]}
        scale={[1.5, 0.5, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert003.geometry}
        material={materials.Land}
        position={[-8.8269, -1.3876, 39.8601]}
        rotation={[0, -0.0984, 0]}
        scale={[3.8951, 0.6348, 0.6348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere017.geometry}
        material={materials.Island}
        position={[-9.9272, -8.1127, 42.5524]}
        rotation={[-0.0409, 0.9645, -0.095]}
        scale={[0.1697, 0.8948, 0.5822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert001.geometry}
        material={materials.Land}
        position={[38.7144, -3.8209, 27.4974]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere007.geometry}
        material={materials.Island}
        position={[38.124, -5.5311, 28.0075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern.geometry}
        material={materials.Lantern}
        position={[5.7683, 2.0203, -8.8391]}
        rotation={[0, -0.531, 0]}
        scale={1.8125}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp.geometry}
          material={materials['Lentern Glow']}
          position={[0.0023, 0.9426, 0.0067]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern001.geometry}
        material={materials.Lantern}
        position={[-9.2058, 1.561, 13.2906]}
        rotation={[0, -1.3636, 0]}
        scale={1.8125}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp001.geometry}
          material={materials['Lentern Glow']}
          position={[0.0023, 0.9426, 0.0067]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern002.geometry}
        material={materials.Lantern}
        position={[9.6887, 1.7874, 11.1489]}
        rotation={[0, -0.531, 0]}
        scale={1.8125}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp002.geometry}
          material={materials['Lentern Glow']}
          position={[0.0023, 0.9426, 0.0067]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern003.geometry}
        material={materials.Lantern}
        position={[41.2451, -2.218, 33.1604]}
        rotation={[0, -0.531, 0]}
        scale={1.8125}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp003.geometry}
          material={materials['Lentern Glow']}
          position={[0.0023, 0.9426, 0.0067]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lantern004.geometry}
        material={materials.Lantern}
        position={[-1.7765, -2.4243, 44.607]}
        rotation={[0, -0.531, 0]}
        scale={1.8125}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lamp004.geometry}
          material={materials['Lentern Glow']}
          position={[0.0023, 0.9426, 0.0067]}
          scale={0.05}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert.geometry}
        material={materials.Tree}
        position={[-12.9117, 0.3202, 4.2261]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere015.geometry}
        material={materials.Leave}
        position={[-14.9857, 10.6552, -1.1048]}
        rotation={[0.2012, 0.0665, -1.0174]}
        scale={[0.6463, 0.6978, 0.7815]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere016.geometry}
        material={materials.Leave}
        position={[-13.388, 8.5471, -2.5374]}
        rotation={[0.1853, -0.103, -1.834]}
        scale={[0.3985, 0.4303, 0.4819]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere018.geometry}
        material={materials.Leave}
        position={[-14.5087, 9.7889, -2.5124]}
        rotation={[0.221, -0.4284, -0.9107]}
        scale={[0.7152, 0.7722, 0.8648]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere019.geometry}
        material={materials.Leave}
        position={[-14.1881, 10.1442, 1.8878]}
        rotation={[0.2012, 0.0665, -1.0174]}
        scale={[0.7635, 0.9957, 0.784]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere020.geometry}
        material={materials.Leave}
        position={[-14.5075, 11.5848, 0.4578]}
        rotation={[0.1853, -0.103, -1.834]}
        scale={[0.3985, 0.4303, 0.4819]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere021.geometry}
        material={materials.Leave}
        position={[-14.1043, 9.9531, 0.4536]}
        rotation={[-0.799, -0.103, -1.834]}
        scale={[0.3985, 0.4303, 0.4819]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere022.geometry}
        material={materials.Leave}
        position={[-14.1923, 13.9535, 4.0675]}
        rotation={[0.8341, -0.7562, -0.6254]}
        scale={[0.9264, 1.2081, 0.9512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere023.geometry}
        material={materials.Leave}
        position={[-13.7581, 11.6264, 3.2475]}
        rotation={[-2.2076, 0.1022, 2.1015]}
        scale={[0.8167, 1.0651, 0.8386]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere024.geometry}
        material={materials.Leave}
        position={[-14.1892, 10.1435, 3.8718]}
        rotation={[0.2012, 0.0665, -1.0174]}
        scale={[0.6463, 0.6978, 0.7815]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere025.geometry}
        material={materials.Leave}
        position={[-14.8344, 12.7237, 6.1823]}
        rotation={[0.6846, -0.5508, -0.8694]}
        scale={[0.8562, 1.1167, 0.8792]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere026.geometry}
        material={materials.Leave}
        position={[-14.7998, 11.1106, 6.5615]}
        rotation={[-0.0171, -0.5, -2.3545]}
        scale={[0.3985, 0.4303, 0.4819]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere027.geometry}
        material={materials.Leave}
        position={[-15.6641, 13.5084, 8.9816]}
        rotation={[-1.1956, -1.159, -1.7998]}
        scale={[0.9264, 1.2081, 0.9512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere028.geometry}
        material={materials.Leave}
        position={[-17.3635, 10.5417, 10.3627]}
        rotation={[0.2012, 0.0665, -1.0174]}
        scale={[0.6463, 0.6978, 0.7815]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere029.geometry}
        material={materials.Leave}
        position={[-16.5307, 11.646, 9.8343]}
        rotation={[-0.799, -0.103, -1.834]}
        scale={[0.3985, 0.4303, 0.4819]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere030.geometry}
        material={materials.Leave}
        position={[-15.9421, 7.4917, 9.1334]}
        rotation={[-0.7634, 0.2268, -0.5473]}
        scale={[0.8869, 0.9576, 1.0724]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere031.geometry}
        material={materials.Leave}
        position={[-14.4239, 5.9156, 7.2974]}
        rotation={[0.2348, 0.4922, -1.3126]}
        scale={[0.5549, 0.5991, 0.671]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere032.geometry}
        material={materials.Leave}
        position={[-19.6162, 11.6269, 4.171]}
        rotation={[-2.4957, -1.1097, 1.987]}
        scale={[0.8848, 1.154, 0.9086]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere033.geometry}
        material={materials.Leave}
        position={[-16.3446, 12.2793, 2.7964]}
        rotation={[2.8826, -0.1487, 1.8018]}
        scale={[0.7106, 0.9267, 0.7297]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere034.geometry}
        material={materials.Leave}
        position={[-17.6139, 13.3948, 6.3895]}
        rotation={[-1.5921, -1.2893, -2.0776]}
        scale={[0.9264, 1.2081, 0.9512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere035.geometry}
        material={materials.Leave}
        position={[-17.1937, 12.8334, 9.1579]}
        rotation={[-0.7634, 0.2268, -0.5473]}
        scale={[0.7777, 0.8396, 0.9403]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere036.geometry}
        material={materials.Leave}
        position={[-17.0567, 13.9229, 3.8261]}
        rotation={[0.1853, -0.103, -1.834]}
        scale={[0.3985, 0.4303, 0.4819]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere037.geometry}
        material={materials.Leave}
        position={[-18.9756, 12.1543, 1.0458]}
        rotation={[-0.4989, 1.2495, -0.4811]}
        scale={[0.5549, 0.5991, 0.671]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert004.geometry}
        material={materials.Tree}
        position={[-15.2622, -3.7563, 45.9584]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere038.geometry}
        material={materials.Leave}
        position={[-13.8564, 8.3399, 50.3926]}
        scale={0.962}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere039.geometry}
        material={materials.Leave}
        position={[-16.0882, 9.0293, 48.038]}
        rotation={[0.378, 0, 0]}
        scale={[1.7235, 1.7235, 2.6516]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere040.geometry}
        material={materials.Leave}
        position={[-16.8212, 7.5544, 45.8575]}
        rotation={[0.1126, 0.8925, 0]}
        scale={[1.5238, 1.087, 3.9816]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere041.geometry}
        material={materials.Leave}
        position={[-19.3242, 6.6545, 42.3355]}
        rotation={[-2.6245, 1.3405, 2.5702]}
        scale={[1.3164, 0.5679, 1.9709]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere042.geometry}
        material={materials.Leave}
        position={[-22.1763, 5.0902, 41.3508]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere043.geometry}
        material={materials.Leave}
        position={[-15.0203, 8.9166, 7.7507]}
        rotation={[0.8482, 0.0606, -0.246]}
        scale={[0.8562, 1.1167, 0.8792]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Water}
        position={[-12.3952, -3.9688, 40.9287]}
        scale={[6.5202, 6.5202, 5.1822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere044.geometry}
        material={materials.Rock}
        position={[-12.0895, -3.1156, 48.8353]}
        rotation={[0, 0, 0.3618]}
        scale={[1.1926, 1.5393, 0.7331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere045.geometry}
        material={materials.Rock}
        position={[-9.9445, -2.8448, 49.4573]}
        rotation={[-0.1315, -0.0959, -0.4069]}
        scale={[1.1926, 1.5393, 0.7331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere046.geometry}
        material={materials.Rock}
        position={[-15.6101, -3.6882, 34.8239]}
        scale={[0.5351, 0.2206, 0.3394]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere047.geometry}
        material={materials.Rock}
        position={[-11.6112, -3.6882, 34.8239]}
        scale={[0.4071, 0.1385, 0.4329]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere048.geometry}
        material={materials.Rock}
        position={[-1.8485, -3.7423, 39.2336]}
        scale={[0.6564, 0.1432, 0.3316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere049.geometry}
        material={materials.Rock}
        position={[-2.4813, 0.1887, 20.0572]}
        rotation={[-0.2084, -0.286, 0.0653]}
        scale={[0.7182, 0.1158, 0.4468]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere050.geometry}
        material={materials.Rock}
        position={[-2.406, -0.119, 21.9405]}
        rotation={[-0.0567, -0.4644, 0.1684]}
        scale={[1.3323, 0.1761, 0.5237]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere051.geometry}
        material={materials.Rock}
        position={[-2.704, -0.6892, 24.1138]}
        rotation={[-0.0821, -0.5177, 0.1688]}
        scale={[1.6848, 0.2227, 0.6623]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere052.geometry}
        material={materials.Rock}
        position={[-3.2733, -1.1297, 26.7923]}
        rotation={[0.0316, -0.6199, 0.1947]}
        scale={[1.6848, 0.2227, 0.6623]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere053.geometry}
        material={materials.Rock}
        position={[-4.2172, -1.5866, 29.4949]}
        rotation={[0.8722, -1.3714, 1.0694]}
        scale={[1.1595, 0.2208, 1.217]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere054.geometry}
        material={materials.Rock}
        position={[-6.3721, -2.6949, 31.6472]}
        rotation={[2.47, -1.3524, 2.7807]}
        scale={[1.1595, 0.2208, 1.217]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere055.geometry}
        material={materials.Rock}
        position={[-8.0347, -3.5631, 33.9912]}
        rotation={[2.47, -1.3524, 2.7807]}
        scale={[1.3129, 0.2501, 1.378]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere056.geometry}
        material={materials.Rock}
        position={[20.5824, 0.5747, 2.0679]}
        scale={[0.6139, 0.1844, 0.6139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere057.geometry}
        material={materials.Rock}
        position={[22.9645, 0.1787, 2.7639]}
        rotation={[0, -0.2542, 0]}
        scale={[0.5765, 0.2356, 0.7933]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere058.geometry}
        material={materials.Rock}
        position={[25.4371, -0.3296, 3.8743]}
        rotation={[0, -0.4236, 0]}
        scale={[0.8456, 0.2356, 1.4588]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere059.geometry}
        material={materials.Rock}
        position={[28.4006, -0.7938, 5.1727]}
        rotation={[0.1989, -0.7147, 0.2433]}
        scale={[1.0495, 0.2924, 1.8105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere060.geometry}
        material={materials.Rock}
        position={[31.5823, -0.9178, 8.1599]}
        rotation={[0.2588, -0.9844, 0.3219]}
        scale={[1.095, 0.3051, 1.8889]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere061.geometry}
        material={materials.Rock}
        position={[34.5624, -1.4218, 11.1218]}
        rotation={[0.444, -1.1077, 0.5826]}
        scale={[1.1603, 0.3233, 2.0017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere062.geometry}
        material={materials.Rock}
        position={[35.7253, -2.1081, 14.9804]}
        rotation={[0.5572, -1.1994, 0.7062]}
        scale={[1.1603, 0.3233, 2.0017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere063.geometry}
        material={materials.Rock}
        position={[36.7198, -2.9891, 18.3567]}
        rotation={[1.4769, -1.4586, 1.6295]}
        scale={[1.1603, 0.3233, 2.0017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere064.geometry}
        material={materials.Rock}
        position={[36.8349, -3.3167, 21.3497]}
        rotation={[1.4769, -1.4586, 1.6295]}
        scale={[1.1603, 0.3233, 2.0017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere065.geometry}
        material={materials.Rock}
        position={[7.3453, 0.9093, 14.2734]}
        rotation={[-0.6916, 0.2487, 0.3679]}
        scale={[1.7053, 0.8711, 1.1658]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere066.geometry}
        material={materials.Rock}
        position={[9.694, 0.5099, 13.3174]}
        rotation={[0, 0, -0.2934]}
        scale={[1.2214, 0.5987, 1.1172]}
      />
    </group>
  )
}

useGLTF.preload('/floatingIsland.glb')
