/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const RockModel = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/floatingRocks.glb')
  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere014.geometry}
        material={materials['Island.001']}
        position={[37.468, -7.758, 9.656]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere013.geometry}
        material={materials['Island.001']}
        position={[26.296, -8.841, 13.814]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere012.geometry}
        material={materials['Island.001']}
        position={[25.888, -17.87, 5.525]}
        rotation={[-0.183, 0.142, -2.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere011.geometry}
        material={materials['Island.001']}
        position={[25.242, -15.556, 5.525]}
        rotation={[-1.12, -0.958, -0.384]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere010.geometry}
        material={materials['Island.001']}
        position={[28.27, -14.997, 5.184]}
        rotation={[0, 0, -0.444]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere008.geometry}
        material={materials['Island.001']}
        position={[-5.691, -23.079, -22.187]}
        rotation={[0, 0, -0.256]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere006.geometry}
        material={materials['Island.001']}
        position={[-19.929, -13.385, 21.61]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere005.geometry}
        material={materials['Island.001']}
        position={[-19.264, -17.269, 15.143]}
        rotation={[0, -0.098, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere004.geometry}
        material={materials['Island.001']}
        position={[-19.867, -14.538, 17.409]}
        rotation={[0, -0.098, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere003.geometry}
        material={materials['Island.001']}
        position={[-5.9, -27.926, -22.354]}
        rotation={[1.181, 0.608, -0.824]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002.geometry}
        material={materials['Island.001']}
        position={[-2.688, -25.873, -22.594]}
        rotation={[1.212, 0.154, -1.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={materials['Island.001']}
        position={[-11.618, -29.108, -23.026]}
        rotation={[1.181, 0.608, -0.824]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials['Island.001']}
        position={[-17.217, -12.338, 19.194]}
        rotation={[0, -0.098, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere067.geometry}
        material={materials['Island.001']}
        position={[17.603, -2.087, 11.383]}
        rotation={[-0.993, -0.582, 0.484]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere068.geometry}
        material={materials['Island.001']}
        position={[37.365, 2.511, -0.25]}
        rotation={[1.212, 0.154, -1.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere069.geometry}
        material={materials['Island.001']}
        position={[30.155, 1.818, -9.54]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere070.geometry}
        material={materials['Island.001']}
        position={[14.745, 2.046, -8.857]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere071.geometry}
        material={materials['Island.001']}
        position={[-25.048, -10.939, 24.606]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere072.geometry}
        material={materials['Island.001']}
        position={[-32.276, -12.715, 14.597]}
        rotation={[-1.408, -0.692, -1.467]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere073.geometry}
        material={materials['Island.001']}
        position={[-30.9, 1.44, 11.224]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere074.geometry}
        material={materials['Island.001']}
        position={[-6.711, 0.715, 19.487]}
        rotation={[0, -0.098, 0]}
        scale={0.574}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere075.geometry}
        material={materials['Island.001']}
        position={[-7.154, 1.31, -1.101]}
        rotation={[1.181, 0.608, -0.824]}
        scale={0.442}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere076.geometry}
        material={materials['Island.001']}
        position={[-18.085, 1.986, 5.043]}
        rotation={[2.611, -0.993, 2.717]}
        scale={0.442}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere077.geometry}
        material={materials['Island.001']}
        position={[-31.865, 4.184, -12.301]}
        rotation={[1.181, 0.608, -0.824]}
        scale={0.442}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere078.geometry}
        material={materials['Island.001']}
        position={[-2.657, 9.017, -44.498]}
        rotation={[2.23, -0.993, 2.717]}
        scale={0.442}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere079.geometry}
        material={materials['Island.001']}
        position={[-20.592, 2.691, -41.83]}
        rotation={[-0.444, 0.1, 0.129]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere081.geometry}
        material={materials['Island.001']}
        position={[-20.962, -8.78, -48.041]}
        rotation={[0, 0, -1.215]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere082.geometry}
        material={materials['Island.001']}
        position={[11.149, -19.821, -28.421]}
        rotation={[-0.584, 1.141, 0.937]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere083.geometry}
        material={materials['Island.001']}
        position={[-20.72, -25.884, -19.89]}
        rotation={[1.236, -0.32, -1.164]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere080.geometry}
        material={materials.Rock}
        position={[19.539, 1.862, -26.863]}
        rotation={[0, 0, -0.293]}
        scale={[0.604, 0.296, 0.553]}
      />
    </group>
  )
})

useGLTF.preload('/floatingRocks.glb')
